export const EXAMPLE_REQUEST = "EXAMPLE_REQUEST";
export const EXAMPLE_SUCCESS = "EXAMPLE_SUCCESS";
export const EXAMPLE_ERROR = "EXAMPLE_ERROR";

export const GET_STOCK_REQUEST = "GET_STOCK_REQUEST";
export const GET_STOCK_SUCCESS = "GET_STOCK_SUCCESS";
export const GET_STOCK_ERROR = "GET_STOCK_ERROR";

export const SAVE_STOCK_REQUEST = "SAVE_STOCK_REQUEST";
export const SAVE_STOCK_SUCCESS = "SAVE_STOCK_SUCCESS";
export const SAVE_STOCK_ERROR = "SAVE_STOCK_ERROR";
